version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: discount
      MYSQL_USER: discount
      MYSQL_PASSWORD: secret
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:z
  web:
    build: .
    command: uvicorn --host 0.0.0.0 discount.discount:app
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: discount
      MYSQL_USER: discount
      MYSQL_PASSWORD: secret
